### PR TITLE
Add W=1 to Makefile

### PR DESCRIPTION
**Pull request by aleksamagicka**
Related to #60. Add W=1 to Makefile.

---
Marking as a draft because I'd like to also add C=1, but I had to install sparse myself, so I need to investigate the Github CI.

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
Just one thought: should we add `W=1 C=1` to our Makefile our just to our CI jobs?

The downside I see in forcing the checks in the Makefile is that it'll affect all users of the yet-out-of-tree drivers. Enabling `W=1` is probably not a big deal, but having to install sparse just to build and use the drivers seems inconvenient.

**Comment by aleksamagicka** [comment]
Yeah, I think that's the way to go.

**Comment by jonasmalacofilho** [comment]
Actually, to clarify, on `W=1` alone, I personally prefer to have it always (or at least by default) enabled for me.

But, still, that's not the default in C or kernel land...

**Comment by aleksamagicka** [comment]
> Actually, to clarify, on W=1 alone, I personally prefer to have it always (or at least by default) enabled for me.

Me too, but...

> But, still, that's not the default in C or kernel land...

That's the thing, I've seen drivers in hwmon that fail with W=1 with today's tree. Arguably, if W=1 is in CI, then the code here _should_ pass it, unless the definition of it changes?

C=1 should be left to CI, I think.

**Comment by aleksamagicka** [comment]
> Yeah, I think that's the way to go. Users should be able to compile and insert regardless of us missing an extended declaration or something.

Whoops, should have checked first before making this assumption. Here W=1 just gives a warning, while in the kernel it stops the compilation. In that case, as you said, I think it's OK to turn it on for everyone (as it's useful to have during development), but CI would need to treat the warnings it gives as errors, so there's still a distinction. I'll look into that.

**Comment by aleksamagicka** [comment]
Here's how this looks like:

- [W=1](https://github.com/aleksamagicka/liquidtux/actions/runs/7132271897/job/19422486434#step:11:23) when it fails
- [W=1 fails and C=1 passes](https://github.com/aleksamagicka/liquidtux/actions/runs/7132443428/job/19422997448#step:11)
- [Both pass](https://github.com/aleksamagicka/liquidtux/actions/runs/7132502876/job/19423175414)

sparse seems to generate a lot of warnings that have nothing to do with the drivers in here, so it looks like I'll have to extend the problem matcher to catch messages related to code from this repo.

**Comment by jonasmalacofilho** [comment]
If I'm not mistaken, this can be merged as is. Or do you prefer to first improve the problem matcher?

**Comment by aleksamagicka** [comment]
Let's merge it as is and I'll deal with the problem matcher later (I'm somewhat short on time right now).

**Pull request merged**
